#SPDX-License-Identifier: MIT-0
---
# tasks file for instance

- name: Update cache
  apt:
    update_cache: true

- name: Install Apache (Debian/Ubuntu)

  apt:
    name: apache2
    state: present # Ensure it's installed

- name: Start Apache service
  service:
    name: apache2
    state: started # Ensure it's running
    
- name: Run web server on apache
  template:
    src: ../templates/index.html.j2
    dest: /var/www/html/index.html